/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package eco.app.panel;

import eco.app.helper.SaveData;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Lenovo
 */
public class CustomerPanel extends javax.swing.JPanel {

    private MigLayout layout = new MigLayout("fill", "[]10[]", "0[]0");

    /**
     * Creates new form ProductPanel
     */
    public CustomerPanel() {
        initComponents();
        init();
    }

    private void init() {


        // Change background color button
        btnInsert.setBackground(SaveData.BTN_SUCCESS);
        btnUpdate.setBackground(SaveData.BTN_WARNING);
        btnDelete.setBackground(SaveData.BTN_DANGER);

        // Set layout
        setLayout(layout);
        add(pnCustomerForm, "w 700!, h 100%");
        add(pnListCustomer, "w 100%, h 100%");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnListCustomer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCustom1 = new eco.app.swing.TableCustom();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textFieldCustom1 = new eco.app.swing.TextFieldCustom();
        checkBoxCustom1 = new eco.app.swing.CheckBoxCustom();
        checkBoxCustom2 = new eco.app.swing.CheckBoxCustom();
        pnCustomerForm = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        textFieldCustom2 = new eco.app.swing.TextFieldCustom();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        textFieldCustom3 = new eco.app.swing.TextFieldCustom();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        textFieldCustom4 = new eco.app.swing.TextFieldCustom();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        textFieldCustom5 = new eco.app.swing.TextFieldCustom();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        textFieldCustom6 = new eco.app.swing.TextFieldCustom();
        jPanel3 = new javax.swing.JPanel();
        btnNew = new eco.app.swing.ButtonRandius();
        btnInsert = new eco.app.swing.ButtonRandius();
        btnUpdate = new eco.app.swing.ButtonRandius();
        btnDelete = new eco.app.swing.ButtonRandius();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        pnListCustomer.setBackground(SaveData.BG_CONTENT);

        tableCustom1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Fullname", "Rank", "Coint", "Spent"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableCustom1);

        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("Search:");

        textFieldCustom1.setText("Customer' s name");
        textFieldCustom1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textFieldCustom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCustom1ActionPerformed(evt);
            }
        });

        checkBoxCustom1.setText("Fullname");
        checkBoxCustom1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        checkBoxCustom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxCustom1ActionPerformed(evt);
            }
        });

        checkBoxCustom2.setText("ID");
        checkBoxCustom2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        checkBoxCustom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxCustom2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldCustom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(checkBoxCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkBoxCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(checkBoxCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout pnListCustomerLayout = new javax.swing.GroupLayout(pnListCustomer);
        pnListCustomer.setLayout(pnListCustomerLayout);
        pnListCustomerLayout.setHorizontalGroup(
            pnListCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnListCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnListCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnListCustomerLayout.setVerticalGroup(
            pnListCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnListCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnCustomerForm.setBackground(SaveData.BG_CONTENT);

        jLabel2.setFont(new java.awt.Font("Roboto", 3, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Create New Customer");

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(5, 0, 0, 10));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setText("Fullname: ");
        jLabel4.setMaximumSize(new java.awt.Dimension(150, 17));
        jLabel4.setMinimumSize(new java.awt.Dimension(150, 17));
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 17));
        jPanel4.add(jLabel4, java.awt.BorderLayout.LINE_START);

        textFieldCustom2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel4.add(textFieldCustom2, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setText("Gender:");
        jLabel5.setMaximumSize(new java.awt.Dimension(150, 17));
        jLabel5.setMinimumSize(new java.awt.Dimension(150, 17));
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 17));
        jPanel5.add(jLabel5, java.awt.BorderLayout.LINE_START);

        textFieldCustom3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel5.add(textFieldCustom3, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5);

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setText("Email:");
        jLabel6.setMaximumSize(new java.awt.Dimension(150, 17));
        jLabel6.setMinimumSize(new java.awt.Dimension(150, 17));
        jLabel6.setPreferredSize(new java.awt.Dimension(150, 17));
        jPanel6.add(jLabel6, java.awt.BorderLayout.LINE_START);

        textFieldCustom4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel6.add(textFieldCustom4, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel6);

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setText("Phone:");
        jLabel7.setMaximumSize(new java.awt.Dimension(150, 17));
        jLabel7.setMinimumSize(new java.awt.Dimension(150, 17));
        jLabel7.setPreferredSize(new java.awt.Dimension(150, 17));
        jPanel7.add(jLabel7, java.awt.BorderLayout.LINE_START);

        textFieldCustom5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel7.add(textFieldCustom5, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel7);

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setText("Address:");
        jLabel8.setMaximumSize(new java.awt.Dimension(150, 17));
        jLabel8.setMinimumSize(new java.awt.Dimension(150, 17));
        jLabel8.setPreferredSize(new java.awt.Dimension(150, 17));
        jPanel8.add(jLabel8, java.awt.BorderLayout.LINE_START);

        textFieldCustom6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel8.add(textFieldCustom6, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel8);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        btnNew.setText("New");
        btnNew.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel3.add(btnNew);

        btnInsert.setText("Insert");
        btnInsert.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel3.add(btnInsert);

        btnUpdate.setText("Update");
        btnUpdate.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel3.add(btnUpdate);

        btnDelete.setText("Delete");
        btnDelete.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel3.add(btnDelete);

        jPanel9.setOpaque(false);
        jPanel9.setLayout(new java.awt.BorderLayout(10, 10));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel9.setText("Note:");
        jLabel9.setMaximumSize(new java.awt.Dimension(150, 17));
        jLabel9.setMinimumSize(new java.awt.Dimension(150, 17));
        jLabel9.setPreferredSize(new java.awt.Dimension(150, 17));
        jPanel9.add(jLabel9, java.awt.BorderLayout.LINE_START);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel9.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnCustomerFormLayout = new javax.swing.GroupLayout(pnCustomerForm);
        pnCustomerForm.setLayout(pnCustomerFormLayout);
        pnCustomerFormLayout.setHorizontalGroup(
            pnCustomerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnCustomerFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCustomerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnCustomerFormLayout.setVerticalGroup(
            pnCustomerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCustomerFormLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldCustom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCustom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCustom1ActionPerformed

    private void checkBoxCustom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxCustom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxCustom1ActionPerformed

    private void checkBoxCustom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxCustom2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxCustom2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private eco.app.swing.ButtonRandius btnDelete;
    private eco.app.swing.ButtonRandius btnInsert;
    private eco.app.swing.ButtonRandius btnNew;
    private eco.app.swing.ButtonRandius btnUpdate;
    private eco.app.swing.CheckBoxCustom checkBoxCustom1;
    private eco.app.swing.CheckBoxCustom checkBoxCustom2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel pnCustomerForm;
    private javax.swing.JPanel pnListCustomer;
    private eco.app.swing.TableCustom tableCustom1;
    private eco.app.swing.TextFieldCustom textFieldCustom1;
    private eco.app.swing.TextFieldCustom textFieldCustom2;
    private eco.app.swing.TextFieldCustom textFieldCustom3;
    private eco.app.swing.TextFieldCustom textFieldCustom4;
    private eco.app.swing.TextFieldCustom textFieldCustom5;
    private eco.app.swing.TextFieldCustom textFieldCustom6;
    // End of variables declaration//GEN-END:variables
}
