/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package eco.app.panel;

import eco.app.component.ProductItem;
import eco.app.helper.SaveData;
import eco.app.myswing.ScrollBarCustom;
import eco.app.myswing.TabbedPaneCustom;
import java.awt.Color;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Lenovo
 */
public class OrderPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrderPanel
     */
    private MigLayout layout = new MigLayout("fill", "0[]10[]0", "0[]0");

    public OrderPanel() {
        initComponents();
        init();
    }

    private void init() {
        setBackground(new Color(255, 153, 102));

        setLayout(layout);
        add(pnFindProduct, "w 720!, h 100%");
        add(pnOrder, "w 100%, h 100%");

        // Design ScrollPanel
        ScrollBarCustom sbc = new ScrollBarCustom();
        sbc.setForeground(new Color(0, 102, 255));
        sbc.setBackground(scProduct.getBackground());
        scProduct.setVerticalScrollBar(sbc);

        //
        pnListProduct.setLayout(new MigLayout("fillx, insets ", "0[]0", "[]5[]"));
        addProduct();
    }

    public void addProduct() {
        pnListProduct.add(new ProductItem(), "wrap, w 100%");
        pnListProduct.add(new ProductItem(), "wrap, w 100%");
        pnListProduct.add(new ProductItem(), "wrap, w 100%");
        pnListProduct.add(new ProductItem(), "wrap, w 100%");
        pnListProduct.add(new ProductItem(), "wrap, w 100%");
        pnListProduct.add(new ProductItem(), "wrap, w 100%");
        pnListProduct.add(new ProductItem(), "wrap, w 100%");
        pnListProduct.add(new ProductItem(), "wrap, w 100%");
        pnListProduct.add(new ProductItem(), "wrap, w 100%");
        pnListProduct.add(new ProductItem(), "wrap, w 100%");
        pnListProduct.add(new ProductItem(), "wrap, w 100%");
        pnListProduct.add(new ProductItem(), "wrap, w 100%");
        pnListProduct.add(new ProductItem(), "wrap, w 100%");
        pnListProduct.add(new ProductItem(), "wrap, w 100%");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnFindProduct = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        textFieldCustom1 = new eco.app.myswing.TextFieldCustom();
        buttonRandius1 = new eco.app.myswing.ButtonRandius();
        jLabel1 = new javax.swing.JLabel();
        cboCategory = new javax.swing.JLabel();
        comboBoxCustom1 = new eco.app.myswing.ComboBoxCustom();
        cboBrand = new eco.app.myswing.ComboBoxCustom();
        scProduct = new javax.swing.JScrollPane();
        pnListProduct = new javax.swing.JPanel();
        pnOrder = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCustom1 = new eco.app.myswing.TableCustom();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        textFieldCustom2 = new eco.app.myswing.TextFieldCustom();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        textFieldCustom3 = new eco.app.myswing.TextFieldCustom();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        textFieldCustom4 = new eco.app.myswing.TextFieldCustom();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        textFieldCustom5 = new eco.app.myswing.TextFieldCustom();
        jPanel3 = new javax.swing.JPanel();
        buttonRandius2 = new eco.app.myswing.ButtonRandius();
        buttonRandius3 = new eco.app.myswing.ButtonRandius();
        buttonRandius4 = new eco.app.myswing.ButtonRandius();

        pnFindProduct.setBackground(SaveData.BG_CONTENT );

        jPanel2.setOpaque(false);

        textFieldCustom1.setText("Search product");
        textFieldCustom1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        buttonRandius1.setText("Search");
        buttonRandius1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Brand: ");

        cboCategory.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        cboCategory.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cboCategory.setText("Category: ");

        cboBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboBrandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(textFieldCustom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRandius1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboCategory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboBoxCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRandius1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(comboBoxCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboCategory)
                    .addComponent(cboBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scProduct.setForeground(new java.awt.Color(204, 204, 255));

        pnListProduct.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout pnListProductLayout = new javax.swing.GroupLayout(pnListProduct);
        pnListProduct.setLayout(pnListProductLayout);
        pnListProductLayout.setHorizontalGroup(
            pnListProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 691, Short.MAX_VALUE)
        );
        pnListProductLayout.setVerticalGroup(
            pnListProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );

        scProduct.setViewportView(pnListProduct);

        javax.swing.GroupLayout pnFindProductLayout = new javax.swing.GroupLayout(pnFindProduct);
        pnFindProduct.setLayout(pnFindProductLayout);
        pnFindProductLayout.setHorizontalGroup(
            pnFindProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFindProductLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnFindProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scProduct)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnFindProductLayout.setVerticalGroup(
            pnFindProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFindProductLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scProduct)
                .addContainerGap())
        );

        pnOrder.setBackground(pnFindProduct.getBackground());
        pnOrder.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                pnOrderComponentResized(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 3, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Order Detail");

        tableCustom1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product", "Quantity", "Price", "Total"
            }
        ));
        jScrollPane1.setViewportView(tableCustom1);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(4, 0, 0, 10));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.BorderLayout(25, 0));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setText("Customer: ");
        jLabel3.setMaximumSize(new java.awt.Dimension(100, 17));
        jLabel3.setMinimumSize(new java.awt.Dimension(100, 17));
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 17));
        jPanel4.add(jLabel3, java.awt.BorderLayout.LINE_START);

        textFieldCustom2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textFieldCustom2.setText("Nguyen Van A");
        textFieldCustom2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel4.add(textFieldCustom2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.BorderLayout(25, 0));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setText("Voncher: ");
        jLabel4.setMaximumSize(new java.awt.Dimension(100, 17));
        jLabel4.setMinimumSize(new java.awt.Dimension(100, 17));
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 17));
        jPanel5.add(jLabel4, java.awt.BorderLayout.LINE_START);

        textFieldCustom3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textFieldCustom3.setText("SELL50%");
        textFieldCustom3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel5.add(textFieldCustom3, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5);

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.BorderLayout(25, 0));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setText("Discount: ");
        jLabel5.setMaximumSize(new java.awt.Dimension(100, 17));
        jLabel5.setMinimumSize(new java.awt.Dimension(100, 17));
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 17));
        jPanel6.add(jLabel5, java.awt.BorderLayout.LINE_START);

        textFieldCustom4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textFieldCustom4.setText("-30.000 VND");
        textFieldCustom4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textFieldCustom4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCustom4ActionPerformed(evt);
            }
        });
        jPanel6.add(textFieldCustom4, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6);

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.BorderLayout(25, 0));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setText("Total:");
        jLabel6.setMaximumSize(new java.awt.Dimension(100, 17));
        jLabel6.setMinimumSize(new java.awt.Dimension(100, 17));
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 17));
        jPanel7.add(jLabel6, java.awt.BorderLayout.LINE_START);

        textFieldCustom5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textFieldCustom5.setText("149.699 VND");
        textFieldCustom5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel7.add(textFieldCustom5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel7);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        buttonRandius2.setBackground(SaveData.BTN_DANGER);
        buttonRandius2.setText("Delete");
        buttonRandius2.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        jPanel3.add(buttonRandius2);

        buttonRandius3.setBackground(SaveData.BTN_WARNING
        );
        buttonRandius3.setText("Save");
        buttonRandius3.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        jPanel3.add(buttonRandius3);

        buttonRandius4.setBackground(SaveData.BTN_SUCCESS);
        buttonRandius4.setText("Complete");
        buttonRandius4.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        jPanel3.add(buttonRandius4);

        javax.swing.GroupLayout pnOrderLayout = new javax.swing.GroupLayout(pnOrder);
        pnOrder.setLayout(pnOrderLayout);
        pnOrderLayout.setHorizontalGroup(
            pnOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnOrderLayout.setVerticalGroup(
            pnOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOrderLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldCustom4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCustom4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCustom4ActionPerformed

    private void cboBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboBrandActionPerformed

    private void pnOrderComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnOrderComponentResized
        if (pnOrder.getWidth() <= 300) {
//            changeLayout();
        }
    }//GEN-LAST:event_pnOrderComponentResized


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private eco.app.myswing.ButtonRandius buttonRandius1;
    private eco.app.myswing.ButtonRandius buttonRandius2;
    private eco.app.myswing.ButtonRandius buttonRandius3;
    private eco.app.myswing.ButtonRandius buttonRandius4;
    private eco.app.myswing.ComboBoxCustom cboBrand;
    private javax.swing.JLabel cboCategory;
    private eco.app.myswing.ComboBoxCustom comboBoxCustom1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnFindProduct;
    private javax.swing.JPanel pnListProduct;
    private javax.swing.JPanel pnOrder;
    private javax.swing.JScrollPane scProduct;
    private eco.app.myswing.TableCustom tableCustom1;
    private eco.app.myswing.TextFieldCustom textFieldCustom1;
    private eco.app.myswing.TextFieldCustom textFieldCustom2;
    private eco.app.myswing.TextFieldCustom textFieldCustom3;
    private eco.app.myswing.TextFieldCustom textFieldCustom4;
    private eco.app.myswing.TextFieldCustom textFieldCustom5;
    // End of variables declaration//GEN-END:variables
}
