/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package eco.app.panel;

import eco.app.component.ProductItem;
import eco.app.dao.BrandDao;
import eco.app.dao.CategoryDao;
import eco.app.entity.Brand;
import eco.app.entity.Category;
import eco.app.entity.Product;
import eco.app.helper.MessageHelper;
import eco.app.helper.SaveData;
import eco.app.helper.ShareData;
import eco.app.swing.ScrollBarCustom;
import eco.app.swing.TabbedPaneCustom;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Lenovo
 */
public class ProductPanel extends javax.swing.JPanel {
    
    private List<Category> categories;
    private List<Brand> brands;

    /**
     * Creates new form OrderPanel
     */
    private MigLayout layout = new MigLayout("fill", "0[]10[]0", "0[]0");
    
    public ProductPanel() {
        initComponents();
        init();
    }
    
    private void init() {
        setLayout(layout);
        add(pnFormProduct, "w 650!, h 100%");
        add(pnListProduct, "w 100%, h 100%");
        
        loadComboBox();
    }
    
    private Product readForm() {
        String name = txtName.getText();
        String price = txtPrice.getText();
        String quantity = txtQuantity.getText();
        String description = txtDescription.getText();
        return null;
    }
    
    private boolean validateForm(StringBuilder sb) {
         
        txtName.check(sb, "Name can't empty.\n");
        txtPrice.check(sb, "Price is invalid.\n");
        txtQuantity.check(sb, "Quantity is invalid.\n");
        txtExpiry.check(sb, "The expiry date must be in the form (dd-MM-YYYY).\n");
        txtDiscount.check(sb, "Discount is invalid.\n");
        txtDescription.check(sb, "Description can't empty.\n");
        
        return sb.isEmpty();
    }
    
    private void loadComboBox() {
        try {
            // Load brand
            brands = new BrandDao().getAll();
            DefaultComboBoxModel brandModel = new DefaultComboBoxModel();
            for (Brand br : brands) {
                brandModel.addElement(br);
            }
            cboBrand.setModel(brandModel);

            // Load  category
            categories = new CategoryDao().getAll();
            DefaultComboBoxModel categoryModel = new DefaultComboBoxModel();
            for (Category ct : categories) {
                categoryModel.addElement(ct);
            }
            cboCategory.setModel(categoryModel);
            
        } catch (Exception e) {
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnListProduct = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduct = new eco.app.swing.TableCustom();
        pnFormProduct = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtName = new eco.app.swing.TextFieldCustom();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtPrice = new eco.app.swing.TextFieldCustom();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtQuantity = new eco.app.swing.TextFieldCustom();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtExpiry = new eco.app.swing.TextFieldCustom();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtDiscount = new eco.app.swing.TextFieldCustom();
        jPanel12 = new javax.swing.JPanel();
        checkBoxCustom1 = new eco.app.swing.CheckBoxCustom();
        checkBoxCustom2 = new eco.app.swing.CheckBoxCustom();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cboCategory = new eco.app.swing.ComboBoxCustom();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cboBrand = new eco.app.swing.ComboBoxCustom();
        jPanel13 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtDescription = new eco.app.swing.TextFieldCustom();
        jPanel15 = new javax.swing.JPanel();
        btnNew = new eco.app.swing.ButtonRandius();
        btnInsert = new eco.app.swing.ButtonRandius();
        btnUpdate = new eco.app.swing.ButtonRandius();
        btnDelete = new eco.app.swing.ButtonRandius();
        jPanel14 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNote = new javax.swing.JTextArea();
        buttonGroup1 = new javax.swing.ButtonGroup();

        pnListProduct.setBackground(SaveData.BG_CONTENT     );
        pnListProduct.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                pnListProductComponentResized(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 3, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("List Product");

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Price", "Discount", "Quantity", "Sold"
            }
        ));
        jScrollPane1.setViewportView(tblProduct);

        javax.swing.GroupLayout pnListProductLayout = new javax.swing.GroupLayout(pnListProduct);
        pnListProduct.setLayout(pnListProductLayout);
        pnListProductLayout.setHorizontalGroup(
            pnListProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnListProductLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnListProductLayout.setVerticalGroup(
            pnListProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnListProductLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnFormProduct.setBackground(SaveData.BG_CONTENT);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eco/app/icon/temp-product-item.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 200));
        jLabel1.setMinimumSize(new java.awt.Dimension(200, 200));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel1.add(jLabel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(4, 0, 0, 10));

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setText("Name: ");
        jLabel8.setMaximumSize(new java.awt.Dimension(100, 17));
        jLabel8.setMinimumSize(new java.awt.Dimension(100, 17));
        jLabel8.setPreferredSize(new java.awt.Dimension(100, 17));
        jPanel7.add(jLabel8, java.awt.BorderLayout.LINE_START);

        txtName.setCanEmpty(false);
        txtName.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtName.setValidateAction(ShareData.validateAction);
        jPanel7.add(txtName, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel7);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setText("Price:");
        jLabel5.setMaximumSize(new java.awt.Dimension(100, 17));
        jLabel5.setMinimumSize(new java.awt.Dimension(100, 17));
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 17));
        jPanel4.add(jLabel5, java.awt.BorderLayout.LINE_START);

        txtPrice.setCanEmpty(false);
        txtPrice.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtPrice.setRegex("[0-9]+");
        txtPrice.setValidateAction(ShareData.validateAction);
        jPanel4.add(txtPrice, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setText("Quantity:");
        jLabel6.setMaximumSize(new java.awt.Dimension(100, 17));
        jLabel6.setMinimumSize(new java.awt.Dimension(100, 17));
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 17));
        jPanel5.add(jLabel6, java.awt.BorderLayout.LINE_START);

        txtQuantity.setCanEmpty(false);
        txtQuantity.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtQuantity.setRegex("[0-9]+");
        txtQuantity.setValidateAction(ShareData.validateAction);
        jPanel5.add(txtQuantity, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5);

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setText("Expiry:");
        jLabel7.setMaximumSize(new java.awt.Dimension(100, 17));
        jLabel7.setMinimumSize(new java.awt.Dimension(100, 17));
        jLabel7.setPreferredSize(new java.awt.Dimension(100, 17));
        jPanel6.add(jLabel7, java.awt.BorderLayout.LINE_START);

        txtExpiry.setCanEmpty(false);
        txtExpiry.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtExpiry.setValidateAction(ShareData.validateAction);
        jPanel6.add(txtExpiry, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel6);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Create New Product");

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(3, 0, 0, 10));

        jPanel11.setOpaque(false);
        jPanel11.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel10.setText("Discount:");
        jLabel10.setMaximumSize(new java.awt.Dimension(100, 17));
        jLabel10.setMinimumSize(new java.awt.Dimension(100, 17));
        jLabel10.setPreferredSize(new java.awt.Dimension(100, 17));
        jPanel11.add(jLabel10, java.awt.BorderLayout.LINE_START);

        txtDiscount.setCanEmpty(false);
        txtDiscount.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtDiscount.setValidateAction(ShareData.validateAction);
        jPanel11.add(txtDiscount, java.awt.BorderLayout.CENTER);

        jPanel12.setOpaque(false);
        jPanel12.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        buttonGroup1.add(checkBoxCustom1);
        checkBoxCustom1.setText("By VND");
        checkBoxCustom1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel12.add(checkBoxCustom1);

        buttonGroup1.add(checkBoxCustom2);
        checkBoxCustom2.setText("By %");
        checkBoxCustom2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel12.add(checkBoxCustom2);

        jPanel11.add(jPanel12, java.awt.BorderLayout.LINE_END);

        jPanel3.add(jPanel11);

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.GridLayout(1, 2, 15, 0));

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("Category: ");
        jLabel4.setMaximumSize(new java.awt.Dimension(100, 17));
        jLabel4.setMinimumSize(new java.awt.Dimension(100, 17));
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 17));
        jPanel10.add(jLabel4, java.awt.BorderLayout.LINE_START);
        jPanel10.add(cboCategory, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel10);

        jPanel9.setOpaque(false);
        jPanel9.setLayout(new java.awt.BorderLayout(15, 0));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel9.setText("Brand:");
        jPanel9.add(jLabel9, java.awt.BorderLayout.LINE_START);
        jPanel9.add(cboBrand, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel9);

        jPanel3.add(jPanel8);

        jPanel13.setOpaque(false);
        jPanel13.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel11.setText("Description: ");
        jLabel11.setMaximumSize(new java.awt.Dimension(100, 17));
        jLabel11.setMinimumSize(new java.awt.Dimension(100, 17));
        jLabel11.setPreferredSize(new java.awt.Dimension(100, 17));
        jPanel13.add(jLabel11, java.awt.BorderLayout.LINE_START);

        txtDescription.setCanEmpty(false);
        txtDescription.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtDescription.setValidateAction(ShareData.validateAction);
        jPanel13.add(txtDescription, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel13);

        jPanel15.setOpaque(false);
        jPanel15.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        btnNew.setText("New");
        btnNew.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel15.add(btnNew);

        btnInsert.setBackground(SaveData.BTN_SUCCESS);
        btnInsert.setText("Insert");
        btnInsert.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        jPanel15.add(btnInsert);

        btnUpdate.setBackground(SaveData.BTN_WARNING);
        btnUpdate.setText("Update");
        btnUpdate.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel15.add(btnUpdate);

        btnDelete.setBackground(SaveData.BTN_DANGER);
        btnDelete.setText("Delete");
        btnDelete.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel15.add(btnDelete);

        jPanel14.setOpaque(false);
        jPanel14.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel12.setText("Note: ");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel12.setMaximumSize(new java.awt.Dimension(100, 17));
        jLabel12.setMinimumSize(new java.awt.Dimension(100, 17));
        jLabel12.setPreferredSize(new java.awt.Dimension(100, 17));
        jPanel14.add(jLabel12, java.awt.BorderLayout.LINE_START);

        txtNote.setColumns(20);
        txtNote.setRows(5);
        jScrollPane2.setViewportView(txtNote);

        jPanel14.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnFormProductLayout = new javax.swing.GroupLayout(pnFormProduct);
        pnFormProduct.setLayout(pnFormProductLayout);
        pnFormProductLayout.setHorizontalGroup(
            pnFormProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnFormProductLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnFormProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnFormProductLayout.setVerticalGroup(
            pnFormProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFormProductLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pnListProductComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnListProductComponentResized
        if (pnListProduct.getWidth() <= 300) {
//            changeLayout();
        }
    }//GEN-LAST:event_pnListProductComponentResized

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        
        StringBuilder sb = new StringBuilder();
        validateForm(sb);
        
        MessageHelper.showMessage(null, sb.toString());
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String a = cboCategory.getSelectedItem().toString();
        System.out.println(cboCategory.getSelectedItem().getClass());
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private eco.app.swing.ButtonRandius btnDelete;
    private eco.app.swing.ButtonRandius btnInsert;
    private eco.app.swing.ButtonRandius btnNew;
    private eco.app.swing.ButtonRandius btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private eco.app.swing.ComboBoxCustom cboBrand;
    private eco.app.swing.ComboBoxCustom cboCategory;
    private eco.app.swing.CheckBoxCustom checkBoxCustom1;
    private eco.app.swing.CheckBoxCustom checkBoxCustom2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnFormProduct;
    private javax.swing.JPanel pnListProduct;
    private eco.app.swing.TableCustom tblProduct;
    private eco.app.swing.TextFieldCustom txtDescription;
    private eco.app.swing.TextFieldCustom txtDiscount;
    private eco.app.swing.TextFieldCustom txtExpiry;
    private eco.app.swing.TextFieldCustom txtName;
    private javax.swing.JTextArea txtNote;
    private eco.app.swing.TextFieldCustom txtPrice;
    private eco.app.swing.TextFieldCustom txtQuantity;
    // End of variables declaration//GEN-END:variables
}
