/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package eco.app.component;

import eco.app.panel.CustomerPanel;
import eco.app.swing.ButtonRandius;
import net.miginfocom.swing.MigLayout;
import eco.app.panel.OrderPanel;
import eco.app.panel.ProductPanel;
import eco.app.swing.TabbedPaneCustom;
import java.awt.Font;

/**
 *
 * @author Lenovo
 */
public class Container extends javax.swing.JPanel {

    /**
     * Creates new form Container
     */
    private MigLayout layout;

    public Container() {
        initComponents();
        layout = new MigLayout();

        setLayout(layout);

        ProductPanel panel0 = new ProductPanel();
        CustomerPanel panel1 = new CustomerPanel();
        OrderPanel panel2 = new OrderPanel();

        TabbedPaneCustom tabbedPaneCustom = new TabbedPaneCustom();
        tabbedPaneCustom.setFont(new Font("Roboto", 0, 20));
        add(tabbedPaneCustom, "w 100%, h 100%");
        tabbedPaneCustom.add("Product", panel0);
        tabbedPaneCustom.add("Customer", panel1);
        tabbedPaneCustom.add("Order", panel2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(241, 254, 254));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 884, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized

    }//GEN-LAST:event_formComponentResized


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
